// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhAyUZsQYqcRISeH9p8MkSZiW1YwKOf-Y',
    appId: '1:682821844288:android:e9cb021eb7f8994de34ea5',
    messagingSenderId: '682821844288',
    projectId: 'flutter-chat-app-v3',
    storageBucket: 'flutter-chat-app-v3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDG29EGSD8GH8u1a-2oeNDBT5nuCHBOtQ',
    appId: '1:682821844288:ios:0d1e29ac2ca90c01e34ea5',
    messagingSenderId: '682821844288',
    projectId: 'flutter-chat-app-v3',
    storageBucket: 'flutter-chat-app-v3.appspot.com',
    androidClientId: '682821844288-gf75087243lgqd7chr0cml5admk2427i.apps.googleusercontent.com',
    iosClientId: '682821844288-v405eja88uo33kpbbtsv75s1oiou6j6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppV3',
  );
}
